//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyXeBus
{
    using System;
    using System.Collections.Generic;
    
    public partial class khacHang
    {
        public string vitringoi { get; set; }
        public string TenKhach { get; set; }
        public Nullable<int> Tuoi { get; set; }
        public Nullable<int> GiaBan { get; set; }
    }
}
