//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySach
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CuongNekEntities : DbContext
    {
        public CuongNekEntities()
            : base("name=CuongNekEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<loaisach> loaisach { get; set; }
        public virtual DbSet<NXB> NXB { get; set; }
        public virtual DbSet<sach> sach { get; set; }
        public virtual DbSet<Tacgia> Tacgia { get; set; }
    }
}
