// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace dataSinhVien
{
    public partial class ThongtinsinhvienContext : DbContext
    {
        public ThongtinsinhvienContext()
        {
        }

        public ThongtinsinhvienContext(DbContextOptions<ThongtinsinhvienContext> options)
            : base(options)
        {
        }

        public virtual DbSet<ThongTin> ThongTin { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. See http://go.microsoft.com/fwlink/?LinkId=723263 for guidance on storing connection strings.
                optionsBuilder.UseSqlServer("Data Source=LAPTOP-L4FQB4A7\\SQLEXPRESS;Initial Catalog=thongTinSinhVien;Integrated Security=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ThongTin>(entity =>
            {
                entity.HasNoKey();

                entity.Property(e => e.GioiTinh)
                    .HasColumnName("gioi_tinh")
                    .HasMaxLength(8);

                entity.Property(e => e.HoTen)
                    .HasColumnName("Ho_Ten")
                    .HasMaxLength(30);

                entity.Property(e => e.Khoa)
                    .HasColumnName("khoa")
                    .HasMaxLength(30);

                entity.Property(e => e.Lop)
                    .HasColumnName("lop")
                    .HasMaxLength(8);

                entity.Property(e => e.MaSv)
                    .HasColumnName("Ma_SV")
                    .HasMaxLength(15);

                entity.Property(e => e.NgaySinh)
                    .HasColumnName("Ngay_Sinh")
                    .HasColumnType("date");

                entity.Property(e => e.QuenQuan)
                    .HasColumnName("quen_quan")
                    .HasMaxLength(15);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}