// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace dataSinhVien
{
    public partial class ThongTin
    {
        public string MaSv { get; set; }
        public string HoTen { get; set; }
        public DateTime? NgaySinh { get; set; }
        public string GioiTinh { get; set; }
        public string QuenQuan { get; set; }
        public string Lop { get; set; }
        public string Khoa { get; set; }
    }
}